The logic of the work of the LoginVC and FeedVC has been improved.
RaffArthur/app-life-cycle pull request #3
Opened 2021-01-14 16:30 UTC by RaffArthur

2021-01-18 10:34 UTC, TrueMax requested changes

2021-01-18 10:34 UTC, TrueMax commented on Social Network/Work Flows/Login/Controllers/LogInViewController.swift
> +            return print("Delegate was not found")
Друг за другом идут 2 инструкции `else` в блоках guard, которые возвращают из метода 2 разных значения: в первом случае строку, во втором показывают алерт, это неверно. Метод не имеет возвращаемого значения. До инструкции `return` нужно указать, что делать в блоке `else`.

2021-01-18 10:34 UTC, TrueMax commented on Social Network/Work Flows/Login/LoginChecker/Checker.swift
> +    static var shared: Checker = {
почему `var`? у нас 1 ссылка на единственный экземпляр без шансов на переопределение в будущем, значит, `let`
Смысл паттерна синглтон - в уникальности.

2021-01-18 10:34 UTC, TrueMax commented on Social Network/Work Flows/Tab Bar/TabBarViewController.swift
> +        feedVC.output = postPresenter
В принципе, не ошибкой будет передать `output` как свойство. На будущее нам также пригодится внедрение зависимостей через инициализатор в модуль.

2021-01-24 14:21 UTC, RaffArthur commented on Social Network/Work Flows/Tab Bar/TabBarViewController.swift
> +        feedVC.output = postPresenter
Вот это не понял.
А что с ним там делать?)

2021-01-24 15:53 UTC, merged